### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by jwerle** [sphia/sphia#1]

**Comment by stephenmathieson** [comment]
i'd like to start getting familiar with sophia / sphia.  how are you planning on implementing tests?  i'd like to try my hand at a few.

**Comment by jwerle** [comment]
I haven't thought much into yet. I know the underlying core functions I'd like to test but there are commands like `ls` that are just a `SPHIA_DB_FOREACH` macro:

``` c
SPHIA_DB_FOREACH(key, val, sphia->db) {
  printf("%s = '%s'\n", trim(key), trim(val));
}
```

Feel free to get creative

**Comment by stephenmathieson** [comment]
how would you feel about some integration tests using [bats](https://github.com/sstephenson/bats) or something similar?

simple example:

``` bash

#!/usr/bin/env bats

setup() {
  rm -fr ./test-db
}

@test "set/get a key->value pair" {
  run ./sphia set -k foo -v bar -p ./test-db
  [ $status -eq 0 ]

  run ./sphia get -k foo -p ./test-db
  [ $output = "bar" ]
  [ $status -eq 0 ]
}

```

**Comment by jwerle** [comment]
Lets do it! I like the idea of using bats. I always wanted to. Feel free to take lead on testing if you'd like :)

**Comment by jwerle** [comment]
@stephenmathieson have you seen this? https://github.com/thlorenz/tap.c cc @thlorenz

**Comment by stephenmathieson** [comment]
very cool.  next time i've got some time, i'll give tap.c a try.

nice job @thlorenz

**Comment by thlorenz** [comment]
@stephenmathieson thanks, can't take too much credit though, all I did was add a `package.json` ;).
Not sure if I should include [Makefile.am](https://github.com/thlorenz/multi-tap-example/tree/master/deps/tap) as part of the `src` as well -- thoughts?

**Comment by jwerle** [comment]
I think it should be left out. However, including it in the read me as a suggestive setup would be great! @thlorenz have you played around with sophia yet dude?

**Comment by thlorenz** [comment]
Not yet - am resolved to take the rest of the year to **learn** C first -- including networking with it. Just learned Autotools over the weekend (what a pain compared to npm).

But will have a look once I feel more comfortable with C and its ecosystem ;)

**Comment by jwerle** [comment]
Great! I think there is a lot that could be done with clibs as far as defining what a "lib" (module) is and how they can be integrated into other "libs" (modules) as "packages". I also think the learning part of C is never ending just like with node and it is going to be a pretty cool journey

**Comment by jwerle** [comment]
@thlorenz if you are ever in the neighborhood by Appnexus come drop by for coffee/tea

**Comment by stephenmathieson** [comment]
@thlorenz haha i didnt notice the _forked from..._

i agree with @jwerle in that the makefile should be kept seperate, but a note on the readme would be helpful.

**Comment by thlorenz** [comment]
Good idea guys, [done](https://github.com/thlorenz/tap.c#use-with-automaketools).

@jwerle I'm actually at Times Square almost every day, so it's quite likely I'd be in the vicinity at some point to chat some C over Coffee :)

**Comment by jwerle** [comment]
Great! shoot me an email joseph.werle@gmail.com

**Comment by jwerle** [comment]
hey @larzconwell ! are you interested in joining us with the sphia project?

**Comment by larzconwell** [comment]
@jwerle Yeah sure, it looks interesting! Won't be able to contribute much, but I'll do what I can (:

**Comment by jwerle** [comment]
@larzconwell Great I've added you as collaborator! @thlorenz let me know if you are interested in coffee still!
