### ISSUE TITLE
.sphiarc or some sort of config file

### ISSUE THREAD

**Issue by stephenmathieson** [sphia/sphia#15]
what are your thoughts on some sort of "defaults" for sphia(1) behavior?

we could set the default path of the db you're working with so you don't have to `sphia <cmd> [opts] --path /path/to/my/favorite/db` every time

**~/.sphiarc**

```
db-path = /path/to/my/favorite/db
foo = bar
```

**Comment by jwerle** [comment]
I like this idea a lot and have been thinking about how to implement it. Is the config just a set of `key = value` pairs? Is there some special functionality we can allow? Is it just bash? When is this file loaded?

**Comment by stephenmathieson** [comment]
it could just be bash and set env flags.  that'd probably be the easiest way to go about it.  it'd be kinda ugly though.

unless we're using bash, config could be anything -- json, ini, etc.

**Comment by jwerle** [comment]
We can experiment with this and try a few different approaches. Here is an INI parser I was looking at for todo.c
https://code.google.com/p/inih/

We could write our own parser that evaluates key - value pairs as well

**Comment by larzconwell** [comment]
I quite like the inih library you linked @jwerle, I've used it before and it has a good API. 

If we use it we then have the ability to use `key = value` and if need be later we can work in the more complex:

```
[namespace]
key = value
```

style to combat possible naming conflicts.

We should probably come up with a list of options, their defaults, and possibly any values that override it(such as environment variables, command line flags, etc.).

EDIT: Well json can use objects for namespacing to I guess, but ini has the most simplistic syntax which is great.

**Comment by stephenmathieson** [comment]
+1 for json.  and regarding parsing it, i've been playing with [kgabis/parson](https://github.com/kgabis/parson) which has a very simple api.  object traversal is a bit ugly, but it works well.

**Comment by jwerle** [comment]
hmmmmm I think ini might be easier in less ugly to read. However, this is a discussion and it is just my preference :)

**Comment by larzconwell** [comment]
Alright guys I did this in the `ini_config` branch, 6ba39a73975002fa785e57e1fb379bbaba23dffb

Let me know what you think and if it's good I'll get it merged over.

**Comment by stephenmathieson** [comment]
Few comments from my end, but overall, looks great!

**Comment by jwerle** [comment]
Ditto!

**Comment by larzconwell** [comment]
Alright guys I made the changes you wanted, it looks pretty nice as well!

@stephenmathieson I just wanna let you know about the concern in your [comment](https://github.com/sphia/sphia/commit/6ba39a73975002fa785e57e1fb379bbaba23dffb#commitcomment-4865525). 

When you provide a `--config` option it indeed uses the given config file instead of the default `./.sphiarc` or `~/.sphiarc`. I made sure users could specify different configs, but still have a set of defaults.

**Comment by stephenmathieson** [comment]
LGTM!

**Comment by larzconwell** [comment]
Merged!

**Comment by jwerle** [comment]
sweet!
