### ISSUE TITLE
Why bundle Sophia?

### ISSUE THREAD

**Issue by larzconwell** [sphia/sphia#19]
It would be better if we just linked it instead of bundling the source code, then we don't have to worry about keeping it up to date for say security updates or something major.

What do you all think?

**Comment by stephenmathieson** [comment]
Makes sense to me; I've had the same thought myself.

**Comment by larzconwell** [comment]
Alright cool, tomorrow I'll start working it in at the same time as #12.

@jwerle When you get a chance let me know what you think.

**Comment by jwerle** [comment]
I like it!
