### ISSUE TITLE
Use linenoise for repl

### ISSUE THREAD

**Issue by jwerle** [sphia/sphia#20]
Perheps we should use https://github.com/antirez/linenoise instead of jwerle/repl.h

OR
jwerle/repl.h should use linenoise..?

**Comment by stephenmathieson** [comment]
I'd say repl.h should just place some sugar on linenoise!

**Comment by jwerle** [comment]
I agree !

**Comment by jwerle** [comment]
Closing as this is relevant to jwerle/repl.h
