### ISSUE TITLE
Segmentation fault on invalid command

### ISSUE THREAD

**Issue by jwerle** [sphia/sphia#21]
``` sh
joseph:~/repos/sphia ☀ master
 √ sphia 123
Segmentation fault (core dumped

joseph:~/repos/sphia ☀ master
 × sphia foo
Segmentation fault (core dumped)

```

**Comment by larzconwell** [comment]
Yeah I'm getting this as well. Was gonna look into it but keep forgetting. BTW I made a debug rule so you can easily use gdb :p

**Comment by jwerle** [comment]
@larzconwell yeah it seemed to be partly related to `which.c` what debug rule did you make?

**Comment by larzconwell** [comment]
Ah good catch. `make debug` adds debug symbols and enables `assert` for debugging.

**Comment by jwerle** [comment]
oh nice! is that merged in?

**Comment by larzconwell** [comment]
Yep yep, that was added with my first commit :D

**Comment by jwerle** [comment]
oh haha duh! :D
