### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [sphia/sphia#26]
I would like to point out that identifiers like "[`__SPHIA_ALL_H__`](https://github.com/sphia/sphia/blob/73bb1b2b4d80a585027df3b0f8212ae855e2d4e6/src/api.h#L9)" and "[`__SPHIA_COUNT_H__`](https://github.com/sphia/sphia/blob/946f8198aecf142e983a1c091212ff77384e0457/src/count.h#L9)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by larzconwell** [comment]
Ah good catch, I'll get it. Unless you want to submit a PR?

**Comment by elfring** [comment]
Thanks for your source code improvement.

**Comment by jwerle** [comment]
@elfring thanks for the catch
