### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [sphia/sphia#28]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html) ⇒ [main](https://github.com/sphia/sphia/blob/73bb1b2b4d80a585027df3b0f8212ae855e2d4e6/src/main.c#L59)
- [closedir](http://pubs.opengroup.org/onlinepubs/9699919799/functions/closedir.html) ⇒ [handle_reset](https://github.com/sphia/sphia/blob/946f8198aecf142e983a1c091212ff77384e0457/src/reset.c#L31)

**Comment by jwerle** [comment]
Thanks for the catch. We'll be looking into this
