### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by larzconwell** [sphia/sphia#29]
Most of them occurring in `main`, but possibly in the others as well.

**Comment by jwerle** [comment]
How are you finding them?

**Comment by larzconwell** [comment]
`valgrind --leak-check=full ./sphia` Then you'll get a ton of output and it'll tell you the stack for the memory allocation. It'll also catch some seg faults like free'ing stack memory and stuff like that, that's easy to miss.

**Comment by jwerle** [comment]
Oh cool thanks! We should look into this

**Comment by larzconwell** [comment]
Yeah I'm looking into it now, also reworking the main function so it's a little easier to read and doesn't have a huge set of if's.

**Comment by jwerle** [comment]
Sweet man that is a huge win
