### ISSUE TITLE
`-v' flag not recognized

### ISSUE THREAD

**Issue by jwerle** [sphia/sphia#33]
``` sh
jwerle:~/repos/sphia ☀ master
 √ sphia set -k name -v "Joseph Werle"
path set to /Users/jwerle/repos/sphia
error: Missing '--value <value>' flag
```

**Comment by larzconwell** [comment]
Ah my fault looks like I changed the verbose short option from `-V` to `-v`. Turns out `-V` won't work as the short verbose option because it's taken by the short version option generated automatically by commander.

**Comment by stephenmathieson** [comment]
`-v` was a shorthand for `--value`, right?

**Comment by larzconwell** [comment]
Yeah it still is actually, it's just that it was already taken for verbose when I changed.

We should come up with another letter for short verbose, then we'll be good.

**Comment by jwerle** [comment]
What do you guys suggest for a verbose flag?

**Comment by larzconwell** [comment]
I was thinking e since it's the next letter. The bad thing about short flag names haha always have to end up compromising the principle of least astonishment.

**Comment by jwerle** [comment]
yeah.. it is always such a conundrum
