### ISSUE TITLE
Development process & master merges

### ISSUE THREAD

**Issue by jwerle** [sphia/sphia#35]

**Comment by stephenmathieson** [comment]
IMO, the only commits going into master should be PR merges.

**Comment by jwerle** [comment]
I agree. PR's should have 100% buy in.

**Comment by larzconwell** [comment]
Yeah that's a good idea, I'm bad about committing to master :p

**Comment by jwerle** [comment]
I've started writing a guide for others to quickly become involved.

**Comment by jwerle** [comment]
https://github.com/sphia/sphia/wiki/Contributing

@stephenmathieson @larzconwell  Let me know what you guys think.

**Comment by larzconwell** [comment]
It's really nice, goes over anything I was thinking so +1.
