### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by jwerle** [sphia/sphia#36]

**Comment by stephenmathieson** [comment]
I've got a branch for this, but because we're linking to sophia, it's got all sorts of hackery in it....

**Comment by jwerle** [comment]
Ah that is right... I wonder how we can deal with it..

**Comment by stephenmathieson** [comment]
~~What about a separate "travis" make target which...~~
1. clone sophia
2. builds like [this](https://github.com/sphia/sphia/blob/8e693e4878/Makefile)
3. runs tests

EDIT: won't work because of `#include <sophia/sophia.h>`

**Comment by stephenmathieson** [comment]
@larzconwell any suggestions? :/

**Comment by larzconwell** [comment]
Yeah I think I have an idea, I'll submit a PR in a while. My internet is shit right now ):

**Comment by jwerle** [comment]
@larzconwell woot!!!

**Comment by larzconwell** [comment]
@jwerle @stephenmathieson #42

**Comment by larzconwell** [comment]
Once we get #44 merged in this can be closed, it's green :D
