### ISSUE TITLE
Supporting batch operations

### ISSUE THREAD

**Issue by deepak1556** [sphia/sphia#47]
could we have something like 

```
sphia batchput key value key value
```

**Comment by jwerle** [comment]
I think this would be a neat plugin. 
what do you guys think? @stephenmathieson @larzconwell

Currently if a command `sphia-batchput` exists in the path, the `sphia` command can proxy it. For example:

``` sh
$ sphia batchput <args>
```

Would call:

``` sh
$ sphia-batchput <args>
```

**Comment by stephenmathieson** [comment]
+1 from me.  I'll put something together!

**Comment by stephenmathieson** [comment]
I've created [sphia-batchput](https://github.com/sphia/sphia-batchput) which will do this for you :)

**Comment by deepak1556** [comment]
:+1:  Also i was hoping if transactions are made available in this utility. We could have another plugin which does

```
sphia-begin
> get <args>
> set <args>
> sphia-commit <name>
sphia-rollback <name> //discard
```

If its ok i can give it a try :)

**Comment by stephenmathieson** [comment]
@deepak1556 Are you thinking about REPL-like behaviour?

And huge +1 for `sphia {commit,rollback} <name>`!

**Comment by deepak1556** [comment]
yup :) should i create a new issue for this feature?

**Comment by stephenmathieson** [comment]
Sure, makes sense to me

**Comment by deepak1556** [comment]
Shld i send pull request for Sphia-begin  here or a new repo for the plugin ?

**Comment by jwerle** [comment]
@deepak1556 make a new repo `sphia-begin`. It looks like we will also need `sphia-commit` and `sphia-rollback`.

@stephenmathieson @larzconwell how do you guys feel about a plugin the packages those three commands together. Something like `sphia-transaction`
