### ISSUE TITLE
undefined reference to sp_recover 

### ISSUE THREAD

**Issue by deepak1556** [sphia/sphia#49]
Machine - 2.6.32-220.4.1.el6.x86_64

```
src/status.o: In function `sphia_status':
status.c:(.text+0x5): undefined reference to `sp_recover'
collect2: ld returned 1 exit status
make: *** [src/main] Error 1

```

Removed sp_recover call from src/status.c to build successfully.

**Comment by stephenmathieson** [comment]
Do you have sophia built and installed?

**Comment by deepak1556** [comment]
Yup.

**Comment by jwerle** [comment]
I think this has to do with the shared object built by sophia. The `sp_recover` function isn't external in a shared library. Try removing the shared library from `/usr/local/lib` and keep the static library. Its a hack for now but we need to open an issue with sophia

**Comment by deepak1556** [comment]
yup the hack works :+1:

**Comment by larzconwell** [comment]
I have an issue here referencing the exported symbols issue with shared libraries. https://github.com/pmwkaa/sophia/issues/39

**Comment by jwerle** [comment]
I'm closing this because this is an issue related to sophia. @pmwkaa has said that these fixes will make its way into the next release, which I'm totally stoked for!
