### ISSUE TITLE
Cannot fully clear a database

### ISSUE THREAD

**Issue by stephenmathieson** [sphia/sphia#51]
I've started writing more tests and found this:

``` sh
$ export SPHIA_PATH=foo
$ sphia set --key key-1 --value value-1
key-1 = 'value-1'
$ sphia set --key key-10 --value value-10
key-10 = 'value-10'
$ sphia clear
Cleared sophia database at path 'foo'
$ sphia ls
key-1 = 'value-1'
$ 
```

It looks like `sphia_clear` isn't actually emptying the database.

**Comment by jwerle** [comment]
Hmm.. that is strange. I think get/set might need some attention.

**Comment by stephenmathieson** [comment]
Agreed.  The issue may be my ugly `strlen(key) + 1` thing from awhile back.

In the [sp_set example](http://sphia.org/sp_set.html), `sizeof(type)` is used.  Perhaps we should be trying `sizeof(char *) + strlen(key)`?

**Comment by jwerle** [comment]
I agree. I'm opening an issue for a core refactor

**Comment by jwerle** [comment]
@stephenmathieson It looks like it is a similar key issue again..

This passes:

``` c
sphia_set(sphia, "key-1", "hello world");
sphia_set(sphia, "key-20", "hello world");
```

This fails:

``` c
sphia_set(sphia, "key-1", "hello world");
sphia_set(sphia, "key-10", "hello world");
```

**Comment by jwerle** [comment]
cc @deepak1556
