### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by larzconwell** [sphia/sphia#63]
I'm sure it doesn't compile on windows since we're using things like `unistd.h` which doesn't have a direct Windows equivalent.

Also how the hell do people typically compile on Windows? Whatever they do, we should set that up.

**Comment by jwerle** [comment]
Man I've been wondering the same thing. I don't even know if Sophia supports Windows ! Haha

**Comment by larzconwell** [comment]
It doesn't seem to include `windows.h` anywhere and uses `unistd.h` without checks, so I don't think so.

**Comment by stephenmathieson** [comment]
Nope, there's no Windows support in Sophia.  I believe [this fork](https://github.com/stanhuff/Sophia) has Windows support though.

**Comment by jwerle** [comment]
Ah! Well that's good to know. I never written a single line of C for windows...

**Comment by stephenmathieson** [comment]
C for Windows isn't bad, but the tools available are.  Threads (which we're not using, so no worries) are horrible, however.

You just basically `#include <windows.h>` and get **everything** available to you.

**Comment by deepak1556** [comment]
I wasnt successful in trying that fork. Maybe we shouldnt focus on windows support at the moment.

**Comment by jwerle** [comment]
Yeah lets revisit once Sophia has windows support at the core :)

**Comment by jwerle** [comment]
Closing this issue until its relevant

**Comment by stephenmathieson** [comment]
@jwerle thanks haha I was going to do the same
