### ISSUE TITLE
Calling sub processes

### ISSUE THREAD

**Issue by larzconwell** [sphia/sphia#64]
When calling user supplied sphia commands and soon(#62) all commands, we're using `system`. Which is considered bad practice, because security concerns, memory  concerns and other stuff. 

Of course the way to solve it, is system dependent since Windows does it completely different(not really surprising). So we should make or a find a library to execute programs externally, and return something more useful than just the return code(also, good luck trying to get that ;) such as state for the process like it's pid, env and anything else deemed necessary for general usage.

**Comment by jwerle** [comment]
Maybe we can implement it on our own with popen and pclose ?

http://www.cs.utah.edu/dept/old/texinfo/glibc-manual-0.02/library_23.html

**Comment by stephenmathieson** [comment]
I don't think we should focus too much on Windows support, as Sophia itself doesn't even support it.

**Comment by jwerle** [comment]
I agree. We should focus on `libsphia` and rewriting `sphia(1)`

**Comment by stephenmathieson** [comment]
> such as state for the process like it's pid, env and anything else deemed necessary for general usage

Why do we need this information?  What would we actually need other than return code?

**Comment by jwerle** [comment]
Yeah I was curious too, but I'm sure there could be cases, right?

**Comment by larzconwell** [comment]
I mean if we were to create a library to do it, we should make it for general usage, so we may only need the rc but others may want to get it's pid and stuff.

**Comment by larzconwell** [comment]
But yeah I agree focusing on the other things are more important, I just created the issues for future reference.

**Comment by stephenmathieson** [comment]
+1 for an dependency handling this for us.

**Comment by jwerle** [comment]
+1

**Comment by larzconwell** [comment]
Alright I'll start on that

**Comment by jwerle** [comment]
Closing until we further discuss this issue
