### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by coleifer** [sphia/sphia#70]
I'm working on a wrapper for sophia 1.2.3 and am having trouble understanding some things.
- Are multi-part indexes limited to two sub-indexes, or are arbitrary number supported?
- When setting a key using sp_setstring, it seems like sometimes I need to pass `0` as the last parameter, sometimes the size of the object, sometimes the size of the object + 1...am I misunderstanding?
- When using the u32 and u64 index types, does this apply to only the key, or both the key and the value?

**Comment by coleifer** [comment]
I've also released some python bindings for 1.2.3: https://github.com/coleifer/sophy

**Comment by pmwkaa** [comment]
Great news! thanks) Answering you questions:
1. index key can have any number of key-parts (actually it is limit by the number of 8 at the moment)
2. sp_setstring(object, path, string, size): when you pass size = 0, it tries to do size = strlen(string) automatically, ex: sp_setstring(env, "db", "test", 0)
3. only key-parts have a type, value can have arbitrary data

Is there are any other issues you encounter during the work?

**Comment by coleifer** [comment]
Well, I've noticed that when setting the key/value on a new `sp_object` for insertion into the database it seems I have to set the length explicitly to (string length + 1). When setting configuration values, though, it seems to be fine to pass `0` for the last parameter.

Similarly, when using `sp_getstring` I have to take the returned length - 1. This may be due to weirdness with the way Cython handles C strings, not sure.

OK so other weird things:
- How does setting the db format to `document` (as opposed to `kv`) work? It seems like it is not working for me. I'm able to set the format and insert data, but for whatever reason I'm not able to retrieve values with `sp_get`. Do I need to pass both the key and value to `sp_get` when using the document format?
- I seem to recall running into errors when I tried using more than 2 indexes. I followed the convention and created a `key_c`...I blew away the code because it wasn't working so I'll have to put something together to re-test it.
- How do `u32` and `u64` index types work? Do I still use `sp_setstring()` to set the key, even though it's a `uint32_t` type?

This is a super cool database you've created, but to be honest, the docs are really thin. It'd be great if you put time into making them better, I know it would help adoption of your database. There are not enough examples. I've turned to just trying to read the test-cases to see how things actually work since the docs only cover a tiny fraction of use-cases.

Lastly, what's the story with 2.0? I wrote my bindings for 1.2.3, but if you're planning to make 2.0 stable soon then should I be writing against master?

Again, thank you for the hard work, this is a really nice library!

**Comment by pmwkaa** [comment]
**document storage**

Basic idea behind document storage is that keys become pointers inside value, this allows not to copy keys twice.

For example: we want to efficiently store json (or bson) in database. If we do this using key-value way, to save space we need to copy keys from json and remove them from value. In case of document storage, keys will now point exactly into keys stored in value.

**multi-part keys**

At the moment Sophia does not support secondary indexes. But there are support for multi-part keys.

For example: lets assume we have two key-parts: 1. string, 2. is u64
First key part is arbitrary email, and second one is some event id. Two parts create a unique key together and both parts are involved in comparison during a key search, iteration, etc.

key: { "name@domain.com", &event_u64_id }
value: raw_bytes

One of features in that scheme, is that we can enable compression_key = 1 and compress part duplicates to save space.

Yes, we have to use sp_setstring(obj, "key_b", &event_u64_id) for u32 and u64 keys. I might add support for sp_setint(obj, "key_b"...) to make it more easy to use.

**v2.1**

Yes, it is a good idea to use it against master. It will be released in next month.
Next release will have slight API changes. There will be no sp_batch() (transactions now will be used instead, sorry). sp_object() is renamed into sp_document(). That's probably it, you can check it out here: https://github.com/pmwkaa/sophia/blob/master/sophia/sophia/sophia.h

**documentation**

I'm really listen to any comments about usability and documentation. I'm really want to make it enjoyable to use as possible. In v123 i've decied to remove API section from documentation which were a bad move:) I will definately bring it back for every function with detailed examples (there are also examples in source code).

I'm really like how rust-book documentation is made: https://doc.rust-lang.org/nightly/book/README.html . I'm thinking to switch to toc-on-the-left layout too.

If you might have a time, could you take a peek look at 'Table of Content' of Sophia documentation:
http://sphia.org/documentation.html  What sections would you add or remove, etc? Fresh look matters.

Thanks) I'm glad that you liked Sophia. I will publish link to the bindings soon.

**Comment by coleifer** [comment]
Thank you for the response! I really appreciate you taking the time to explain all this to me. I don't know if these are stupid questions, but perhaps some of them could've been answered by writing more thorough documentation.

So with regards to 1.2.3 versus 2.x -- I suppose I will update my bindings to use `master` but I'm a bit uncertain what's different between the versions besides the two things you mention (`sp_document` and no `sp_batch`). Is the online documentation for 1.2.3 or 2.x? That's something else you may want to consider -- indicating and supporting docs for multiple versions.

I am the co-creator of a site http://readthedocs.org/ and have several popular open-source projects. I'm a firm believer in having high quality documentation, both prose and API descriptions. At the bare minimum, I think having overview of the API with params and code examples is a must for any project that will be successful. I hope you'll consider my comment not as a criticism, but instead as a complement -- I really want to use your project and I want it to be very successful, it seems very cool, but it really needs better docs.

**Comment by coleifer** [comment]
Finally, do you mind putting together a small code example showing the use of a multi-part key consisting of 3 parts? Looking at the tests I see examples using 2-part keys, but none using 3.

**Comment by pmwkaa** [comment]
Great! So i'm in the right place :)

Unfortunately there are no documentation for upcoming release, so it is the good time to talk about things that should be changed. It will be based on documentation for v1.2.3, upgraded, modified and so on.

Next release will be significant to me, because it will be the first release which will have official mark  'production ready' and will have a lot of great distinguish features.

Sure, I've made a small example of multi-part keys usage: https://github.com/pmwkaa/sophia/blob/master/example/multipart.c

Maybe it will be easier to switch to email or mail-list discussion?

**Comment by coleifer** [comment]
I did notice one bug after changing from 1.2.3 to 2.1.1. Let's say I have a string index type and my data looks like:

```
aa => a
bb => b
cc => c
dd => d
```

In 1.2.3 I could do something like:

```
cursor = sp_cursor()
setstring(cursor, 'key', 'bb')
setstring(cursor, 'order', '<=')
while (...):
    print key and value
```

And the output would be:

```
bb -> b
aa -> a
```

After upgrading to 2.1.1, only "aa -> a" is output, even though I specified `<=` and the key "bb" is an exact match. To work around this, I found that appending `\x01` to the key will get the desired results ("bb" is included). However I think this is a bug.

It only seems to affect cursors iterating in reverse, ascending works fine.

**Comment by coleifer** [comment]
I can create a separate issue for the above comment if you'd prefer. And yes, we can continue our discussion about 2.x and docs on the mailing list.

**Comment by pmwkaa** [comment]
Ok, i've made a test for v2.1 which looks fine from first sight. Could this be related to python-c string transition (zero eol sign, for example)?

**Comment by coleifer** [comment]
Well, I would've thought something similar, but because it worked fine on 1.2.3 and only stopped working with 2.1.1 I thought perhaps it was a Sophia issue. I looked at your test-case, though, and clearly the issue is somewhere in my code. Sorry for sending you on a fool's errand!

**Comment by pmwkaa** [comment]
No worries, it is better to recheck to be sure :)
